# Generated by scripts/render-github-proxy.sh. Do not edit.
Port 8888
Listen 0.0.0.0
Timeout 600
MaxClients 200
DisableViaHeader Yes

# HTTPS / HTTP CONNECT only. Docker 拉镜像不要走这里。
ConnectPort 443
ConnectPort 80

Allow 127.0.0.1
Allow ::1
# {{ALLOW_LINES}}
